# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"

  config.vm.network "forwarded_port", guest: 9090, host: 9090

  config.vm.provision "shell", path: "vagrant_bootstrap.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 768
    v.cpus = 1
  end
end
